#!/usr/bin/env python3
"""shorthand - an abook-style CLI tool for managing your shell aliases."""
import curses
import json
import sys
from pathlib import Path

DATA_DIR = Path.home() / ".shorthand"
DATA_FILE = DATA_DIR / "aliases.json"
EXPORT_FILE = DATA_DIR / "aliases.sh"


# ---------- storage ----------

def load_aliases():
    if not DATA_FILE.exists():
        return {}
    try:
        with open(DATA_FILE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def export_aliases(aliases):
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(EXPORT_FILE, "w") as f:
        f.write("# Generated by shorthand - do not edit directly\n")
        for name, cmd in sorted(aliases.items()):
            escaped = cmd.replace("'", "'\\''")
            f.write(f"alias {name}='{escaped}'\n")


def save_aliases(aliases):
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(DATA_FILE, "w") as f:
        json.dump(aliases, f, indent=2, sort_keys=True)
    export_aliases(aliases)


# ---------- non-interactive CLI ----------

def cli_add(name, command):
    aliases = load_aliases()
    aliases[name] = command
    save_aliases(aliases)
    print(f"Added: {name} -> {command}")


def cli_rm(name):
    aliases = load_aliases()
    if name in aliases:
        del aliases[name]
        save_aliases(aliases)
        print(f"Removed: {name}")
    else:
        print(f"No such alias: {name}")


def cli_list():
    aliases = load_aliases()
    if not aliases:
        print("No aliases stored yet. Try: shorthand add ll 'ls -la'")
        return
    width = max(len(n) for n in aliases)
    for name, cmd in sorted(aliases.items()):
        print(f"{name.ljust(width)}  ->  {cmd}")


def cli_export():
    export_aliases(load_aliases())
    print(f"Exported to {EXPORT_FILE}")


def cli_install():
    export_aliases(load_aliases())
    rc_candidates = [Path.home() / ".bashrc", Path.home() / ".zshrc"]
    line = f'\n# shorthand aliases\n[ -f "{EXPORT_FILE}" ] && source "{EXPORT_FILE}"\n'
    updated = []
    for rc in rc_candidates:
        if rc.exists():
            content = rc.read_text()
            if str(EXPORT_FILE) in content:
                continue
            with open(rc, "a") as f:
                f.write(line)
            updated.append(str(rc))
    if updated:
        print("Wired shorthand into: " + ", ".join(updated))
        print("Run `source ~/.bashrc` (or open a new shell) to activate.")
    else:
        print("Already installed, or no ~/.bashrc / ~/.zshrc found.")
        print(f'Add manually:  [ -f "{EXPORT_FILE}" ] && source "{EXPORT_FILE}"')


# ---------- interactive TUI (abook-style) ----------

class ShorthandTUI:
    def __init__(self, stdscr):
        self.stdscr = stdscr
        self.aliases = load_aliases()
        self.names = sorted(self.aliases)
        self.pos = 0
        self.top = 0
        self.filter = ""
        curses.curs_set(0)
        curses.start_color()
        curses.use_default_colors()
        curses.init_pair(1, curses.COLOR_BLACK, curses.COLOR_CYAN)  # selection / header
        curses.init_pair(4, curses.COLOR_YELLOW, -1)                # status bar

    def visible_names(self):
        if self.filter:
            f = self.filter.lower()
            return [n for n in self.names if f in n.lower() or f in self.aliases[n].lower()]
        return self.names

    def draw(self):
        stdscr = self.stdscr
        stdscr.erase()
        h, w = stdscr.getmaxyx()

        stdscr.attron(curses.color_pair(1))
        stdscr.addstr(0, 0, " shorthand - alias manager ".ljust(w))
        stdscr.attroff(curses.color_pair(1))

        names = self.visible_names()
        list_h = max(1, h - 3)
        if self.pos >= len(names):
            self.pos = max(0, len(names) - 1)
        if self.pos < self.top:
            self.top = self.pos
        if self.pos >= self.top + list_h:
            self.top = self.pos - list_h + 1

        namecol = min(max((len(n) for n in names), default=10), w // 3)

        if not names:
            stdscr.addstr(1, 2, "No aliases yet - press 'a' to add one.")
        for i, name in enumerate(names[self.top:self.top + list_h]):
            row = 1 + i
            line = f" {name.ljust(namecol)} | {self.aliases[name]}"
            line = line[:w - 1].ljust(w - 1)
            if self.top + i == self.pos:
                stdscr.attron(curses.color_pair(1))
                stdscr.addstr(row, 0, line.ljust(w))
                stdscr.attroff(curses.color_pair(1))
            else:
                stdscr.addstr(row, 0, line)

        status = " a:add  e:edit  d:delete  /:search  s:sync shell  q:quit "
        if self.filter:
            status = f" filter: {self.filter} (esc clears) |" + status
        stdscr.attron(curses.color_pair(4))
        stdscr.addstr(h - 1, 0, status[:w - 1].ljust(w - 1))
        stdscr.attroff(curses.color_pair(4))
        stdscr.refresh()

    def prompt(self, label, initial=""):
        h, w = self.stdscr.getmaxyx()
        curses.curs_set(1)
        win = curses.newwin(1, w, h - 2, 0)
        win.keypad(True)
        text = initial
        while True:
            win.erase()
            win.addstr(0, 0, f"{label}{text}")
            win.refresh()
            ch = win.get_wch()
            if ch in ("\n", "\r"):
                break
            if ch == "\x1b":
                text = None
                break
            if ch in ("\x7f", "\b") or ch == curses.KEY_BACKSPACE:
                text = text[:-1]
            elif isinstance(ch, str) and ch.isprintable():
                text += ch
        curses.curs_set(0)
        return text

    def add_entry(self):
        name = self.prompt("Alias name: ")
        if not name:
            return
        cmd = self.prompt("Command: ")
        if cmd is None:
            return
        self.aliases[name] = cmd
        self.names = sorted(self.aliases)
        save_aliases(self.aliases)

    def edit_entry(self):
        names = self.visible_names()
        if not names:
            return
        name = names[self.pos]
        cmd = self.prompt(f"Command for '{name}': ", self.aliases[name])
        if cmd is None:
            return
        self.aliases[name] = cmd
        save_aliases(self.aliases)

    def delete_entry(self):
        names = self.visible_names()
        if not names:
            return
        name = names[self.pos]
        confirm = self.prompt(f"Delete '{name}'? (y/n): ")
        if confirm and confirm.lower() == "y":
            del self.aliases[name]
            self.names = sorted(self.aliases)
            save_aliases(self.aliases)

    def search(self):
        self.filter = self.prompt("Search: ") or ""
        self.pos = 0

    def run(self):
        while True:
            self.draw()
            ch = self.stdscr.get_wch()
            names = self.visible_names()
            if ch in ("q", "Q"):
                break
            elif ch in ("k",) or ch == curses.KEY_UP:
                self.pos = max(0, self.pos - 1)
            elif ch in ("j",) or ch == curses.KEY_DOWN:
                self.pos = min(max(0, len(names) - 1), self.pos + 1)
            elif ch in ("a", "A"):
                self.add_entry()
            elif ch in ("e", "E", "\n"):
                self.edit_entry()
            elif ch in ("d", "D"):
                self.delete_entry()
            elif ch == "/":
                self.search()
            elif ch == "\x1b":
                self.filter = ""
                self.pos = 0
            elif ch in ("s", "S"):
                cli_install()
                self.prompt("Synced to shell rc. Press Enter: ")


def run_tui():
    curses.wrapper(lambda stdscr: ShorthandTUI(stdscr).run())


USAGE = """shorthand - abook-style manager for your shell aliases

Usage:
  shorthand                launch the interactive UI
  shorthand add NAME CMD   add or update an alias
  shorthand rm NAME        remove an alias
  shorthand list           list all aliases
  shorthand export         write ~/.shorthand/aliases.sh
  shorthand install        wire aliases.sh into ~/.bashrc / ~/.zshrc
"""


def main():
    args = sys.argv[1:]
    if not args:
        run_tui()
        return
    cmd, *rest = args
    if cmd == "add" and len(rest) >= 2:
        cli_add(rest[0], " ".join(rest[1:]))
    elif cmd == "rm" and rest:
        cli_rm(rest[0])
    elif cmd == "list":
        cli_list()
    elif cmd == "export":
        cli_export()
    elif cmd == "install":
        cli_install()
    else:
        print(USAGE)


if __name__ == "__main__":
    main()
